Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriFitWeb.Data;
using NutriFitWeb.Models;
using NutriFitWeb.Services;

namespace NutriFitWeb.Controllers
{
    /// <summary>
    /// AdminsController class, derives from Controller.
    /// </summary>
    public class AdminsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IInteractNotification _interactNotification;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        public AdminsController(ApplicationDbContext context,
            IInteractNotification interactNotification)
        {
            _context = context;
            _interactNotification = interactNotification;
        }

        /// <summary>
        /// Shows all users for in the application from a Admin perspective
        /// </summary>
        /// <param name="searchString"></param>
        /// <param name="currentFilter"></param>
        /// <param name="pageNumber"></param>
        /// <returns>A Paginated ViewResult</returns>
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> ShowAllUsers(string? searchString, string? currentFilter, int? pageNumber)
        {
            if (searchString is not null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IdentityRole? adminRole = await _context.Roles.FirstOrDefaultAsync(a => a.Name == "administrator");
            IQueryable<IdentityUserRole<string>>? admins = null;
            IQueryable<UserAccountModel>? users = null;
            if (adminRole is not null)
            {
                admins = _context.UserRoles.Where(a => a.RoleId == adminRole.Id);
                if (admins is not null)
                {
                    if (!string.IsNullOrEmpty(searchString))
                    {
                        users = _context.Users.Where(p => admins.All(p2 => p2.UserId != p.Id)).Where(a => a.Email.Contains(searchString));
                    }
                    else
                    {
                        users = _context.Users.Where(p => admins.All(p2 => p2.UserId != p.Id));
                    }
                }
            }
            if (users is not null)
            {
                int pageSize = 3;
                return View(await PaginatedList<UserAccountModel>.CreateAsync(users.AsNoTracking(), pageNumber ?? 1, pageSize));
            }
            return NoContent();
        }

        /// <summary>
        /// Deletes a user account.
        /// Only accessible for Administrator role.
        /// </summary>
        /// <param name="id">The user account id</param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> DeleteUserAccount(string? id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _context.Users.FirstOrDefaultAsync(a => a.Id == id);

            if (user is null)
            {
                return NotFound();
            }

            return View(user);
        }

        /// <summary>
        /// Deletes a user account and calls the Http POST method to the API to update the data.
        /// Only accessible for Administrator role.
        /// </summary>
        /// <param name="id">The User account id</param>
        /// <returns>An Action result</returns>
        [HttpPost, ActionName("DeleteUserAccount")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> DeleteUserAccountPost(string? id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            Trainer? trainer = await _context.Trainer.FirstOrDefaultAsync(a => a.UserAccountModel.Id == id);
            Nutritionist? nutritionist = await _context.Nutritionist.FirstOrDefaultAsync(a => a.UserAccountModel.Id == id);
            Gym? gym = await _context.Gym.FirstOrDefaultAsync(a => a.UserAccountModel.Id == id);
            Client? client = await _context.Client.FirstOrDefaultAsync(a => a.UserAccountModel.Id == id);

            if (trainer is not null)
            {
                _context.Trainer.Remove(trainer);
            }
            if (nutritionist is not null)
            {
                _context.Nutritionist.Remove(nutritionist);
            }

            if (client is not null)
            {
                _context.Client.Remove(client);
            }

            if (gym is not null)
            {
                _context.Gym.Remove(gym);
            }

            UserAccountModel? user = await _context.Users.FirstOrDefaultAsync(a => a.Id == id);

            if (user is not null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("ShowAllUsers");
        }

        /// <summary>
        /// Edit the User settings action to redirect to the selected user account.
        /// Only accessible for Administrator role.
        /// </summary>
        /// <param name="id">The User account id</param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> EditUserSettings(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            UserAccountModel? userAccountModel = await _context.Users.FindAsync(id);
            if (userAccountModel is null)
            {
                return NotFound();
            }
            return View(userAccountModel);
        }

        /// <summary>
        /// Edits a user account and calls the Http POST method to the API to update the data.
        /// Only accessible for Administrator role.
        /// </summary>
        /// <param name="id">The User account id</param>
        /// <returns>An Action result</returns>
        [HttpPost, ActionName("EditUserSettings")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> EditUserSettingsPost(string? id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            UserAccountModel? userToUpdate = await _context.Users.FindAsync(id);
            if (userToUpdate is not null && await TryUpdateModelAsync<UserAccountModel>(userToUpdate, "",
                u => u.PhoneNumber, u => u.UserName))
            {
                await _interactNotification.Create($"O administrador alterou parte da sua conta.", userToUpdate);
                await _context.SaveChangesAsync();
                return RedirectToAction("ShowAllUsers");
            }
            return View(userToUpdate);
        }
    }
}

Controllers/ClientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriFitWeb.Data;
using NutriFitWeb.Models;
using NutriFitWeb.Services;

namespace NutriFitWeb.Controllers
{
    /// <summary>
    /// ClientsController Class derives from Controller
    /// </summary>
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserAccountModel> _userManager;
        private readonly IIsUserInRoleByUserId _isUserInRoleByUserId;
        private readonly IPhotoManagement _photoManagement;
        private readonly IInteractNotification _interactNotification;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context">Application DB context</param>
        /// <param name="userManager">User Manager API</param>
        /// <param name="isUserInRoleByUserId">Interface to determine if the user is of a given role</param>
        /// <param name="photoManagement">Photo management Interface</param>
        public ClientsController(ApplicationDbContext context,
            UserManager<UserAccountModel> userManager,
            IIsUserInRoleByUserId isUserInRoleByUserId,
            IPhotoManagement photoManagement,
            IInteractNotification interactNotification)
        {
            _context = context;
            _userManager = userManager;
            _isUserInRoleByUserId = isUserInRoleByUserId;
            _photoManagement = photoManagement;
            _interactNotification = interactNotification;
        }

        /// <summary>
        /// Shows a paginated View of all the clients.
        /// </summary>
        /// <param name="searchString"></param>
        /// <param name="currentFilter"></param>
        /// <param name="pageNumber"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym, nutritionist, trainer")]
        public async Task<IActionResult> ShowClients(string? searchString, string? currentFilter, int? pageNumber)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            if (searchString is not null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IOrderedQueryable<Client>? clients = null;

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (User.IsInRole("gym"))
            {
                clients = GetClientsForGym(searchString, user.Id);
            }
            else if (User.IsInRole("trainer"))
            {
                clients = await GetClientsForTrainer(searchString, user.Id);
            }
            else if (User.IsInRole("nutritionist"))
            {
                clients = await GetClientsForNutritionist(searchString, user.Id);
            }

            if (clients is not null)
            {
                int pageSize = 3;
                return View(await PaginatedList<Client>.CreateAsync(clients.AsNoTracking(), pageNumber ?? 1, pageSize));
            }
            return NotFound();
        }

        /// <summary>
        /// Shows a specific client details page, based on client id.
        /// </summary>
        /// <param name="id">Client id</param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym, trainer, nutritionist")]
        public async Task<IActionResult> ClientDetails(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            return View(await _context.Client.
                            Include(a => a.UserAccountModel).
                            Include(a => a.Gym).
                            Include(a => a.Trainer).
                            Include(a => a.Nutritionist).
                            Include(a => a.ClientProfilePhoto).
                            FirstOrDefaultAsync(a => a.ClientId == id));
        }

        /// <summary>
        /// Displays the page to change a client's gym status, based on client id.
        /// Only accessible for the Gym role.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="pageNumber"></param>
        /// <param name="currentFilter"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym")]
        public async Task<IActionResult> ChangeClientGymStatus(int? id, int? pageNumber, string? currentFilter)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            Gym? gym = await _context.Gym.FirstOrDefaultAsync(a => a.UserAccountModel.Id == user.Id);
            Client? client = await _context.Client.
            Include(a => a.Gym).
            Include(a => a.Trainer).
            Include(a => a.Trainer!.TrainingPlans).
            Include(a => a.Nutritionist).
            Include(a => a.Nutritionist!.NutritionPlans).
            Include(a => a.TrainingPlanRequests).
            Include(a => a.NutritionPlanRequests).
            Include(a => a.UserAccountModel).
            FirstOrDefaultAsync(a => a.ClientId == id);

            if (client is not null && client.UserAccountModel is not null)
            {
                if (gym is not null && client.Gym is null ||
                                    (client.Gym is not null && client.Gym.UserAccountModel is not null &&
                                    _userManager.GetUserId(User) == client.Gym.UserAccountModel.Id))
                {
                    client.Gym = (client.Gym is null) ? gym : null;
                    if (client.Gym is null)
                    {
                        if (client.Trainer is not null && client.Trainer.TrainingPlans is not null)
                        {
                            client.Trainer.TrainingPlans = client.Trainer.TrainingPlans.Where(a => a.Client != client).ToList();
                        }
                        if (client.Nutritionist is not null && client.Nutritionist.NutritionPlans is not null)
                        {
                            client.Nutritionist.NutritionPlans = client.Nutritionist.NutritionPlans.Where(a => a.Client != client).ToList();
                        }
                        client.Trainer = null;
                        client.WantsTrainer = false;
                        client.Nutritionist = null;
                        client.WantsNutritionist = false;
                        client.TrainingPlanRequests = null;
                        client.NutritionPlanRequests = null;
                        client.DateAddedToGym = null;
                        await _interactNotification.Create("Foi removido do seu ginásio.", client.UserAccountModel);
                    }
                    else
                    {
                        client.DateAddedToGym = DateTime.Now;
                        await _interactNotification.Create($"Foi adicionado ao ginásio {client.Gym.GymName}.", client.UserAccountModel);
                    }
                    _context.Client.Update(client);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("ShowClients", new { pageNumber, currentFilter });
            }
            return NoContent();
        }

        /// <summary>
        /// Displays the page to change a client's trainer status, based on client id.
        /// Only accessible for the Trainer role.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="pageNumber"></param>
        /// <param name="currentFilter"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "trainer")]
        public async Task<IActionResult> ChangeClientTrainerStatus(int? id, int? pageNumber, string? currentFilter)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            Trainer? trainer = await _context.Trainer.Include(a => a.UserAccountModel).FirstOrDefaultAsync(a => a.UserAccountModel.Id == user.Id);
            Client? client = await _context.Client.
            Include(a => a.Trainer).
            Include(a => a.Trainer!.TrainingPlans).
            Include(a => a.UserAccountModel).
            FirstOrDefaultAsync(a => a.ClientId == id);

            if (client is not null && client.UserAccountModel is not null &&
                trainer is not null && trainer.UserAccountModel is not null)
            {
                if (client.Gym == trainer.Gym && client.Trainer is null ||
                (client.Trainer is not null && client.Trainer.UserAccountModel is not null &&
                _userManager.GetUserId(User) == client.Trainer.UserAccountModel.Id))
                {
                    if (client.Trainer is not null && client.Trainer.TrainingPlans is not null)
                    {
                        client.Trainer.TrainingPlans = client.Trainer.TrainingPlans.Where(a => a.Client != client).ToList();
                    }
                    client.Trainer = (client.Trainer is null) ? trainer : null;
                    if (client.Trainer is null)
                    {
                        client.DateAddedToTrainer = null;
                        await _interactNotification.Create($"O {trainer.UserAccountModel.UserName} já não é seu treinador.", client.UserAccountModel);
                    }
                    else
                    {
                        client.DateAddedToTrainer = DateTime.Now;

Views/Clients/EditClientForTrainerAndNutritionist.cshtml
@model NutriFitWeb.Models.Client

@{
    ViewData["Title"] = "Editar perfil do Cliente";
}

<h1>@ViewData["Title"]</h1>

<div class="col-md-8 profileDivs">
    <form asp-action="EditClientForTrainerAndNutritionist">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ClientId" /> 
        <table class="formTables">
                <tr>
                    <th class="alignTableTitles"><label asp-for="Weight" class="control-label listsItemTitle"></label></th>
                    <td>
                        <input asp-for="Weight" class="formsInput" type="number" step="0.1"/>
                        <br />
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <th class="alignTableTitles"><label asp-for="Height" class="control-label listsItemTitle"></label></th>
                    <td>
                        <input asp-for="Height" class="formsInput" />
                        <br />
                        <span asp-validation-for="Height" class="text-danger"></span>
                    </td>
                </tr>
                @if(User.IsInRole("nutritionist")){
                    <tr>
                        <th class="alignTableTitles"><label asp-for="LeanMass" class="control-label listsItemTitle"></label></th>
                        <td>
                            <input asp-for="LeanMass" class="formsInput" type="number" step="0.1"/>
                            <br />
                            <span asp-validation-for="LeanMass" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <th class="alignTableTitles"><label asp-for="FatMass" class="control-label listsItemTitle"></label></th>
                        <td>
                            <input asp-for="FatMass" class="formsInput" type="number" step="0.1"/>
                            <br />
                            <span asp-validation-for="FatMass" class="text-danger"></span>
                        </td>
                    </tr>
                }
                <tr>
                    <th class="alignTableTitles"><label asp-for="OtherClientData" class="control-label listsItemTitle"></label></th>
                    <td>
                        <textarea asp-for="OtherClientData" class="descriptionBox"></textarea>
                        <br />
                        <span asp-validation-for="OtherClientData" class="text-danger"></span>
                    </td>
                </tr>
        </table>

        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </form>
</div>

<div class="backBtnDiv">
    <a asp-action="ShowClients" class="backToListBtn">Voltar</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Clients/EditClientSettings.cshtml
@model NutriFitWeb.Models.Client
@using NutriFitWeb.Models
@using Microsoft.AspNetCore.Identity
@using NutriFitWeb.Services
@inject UserManager<UserAccountModel> UserManager
@inject IPhotoManagement PhotoManagement

@{
    ViewData["Title"] = "Editar perfil do Cliente";
}

<h1>@ViewData["Title"]</h1>

<div class="col-md-8 profileDivs">
    <form asp-action="EditClientSettings" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ClientId" />
        <div class="form-group">
            <label asp-for="ClientProfilePhoto" class="control-label listsItemTitle">Foto de Perfil</label>
            @if (Model.ClientProfilePhoto is not null)
            {
                <div><img class="profilePhoto" src="@Model.ClientProfilePhoto.PhotoUrl" /></div>
            }
            <input type="file" asp-for="ClientProfilePhoto" class="form-control marginFixChooseFile" name="formFile" />
            <span asp-validation-for="ClientProfilePhoto" class="text-danger"></span>
        </div>


        <table class="formTables">
            <tr>
                <th class="alignTableTitles"><label asp-for="ClientFirstName" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="ClientFirstName" class="formsInput" />
                    <br />
                    <span asp-validation-for="ClientFirstName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="ClientLastName" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="ClientLastName" class="formsInput" />
                    <br />
                    <span asp-validation-for="ClientLastName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="ClientSex" class="control-label listsItemTitle"></label></th>
                <td>
                    <select asp-for="ClientSex" class="formsInput" asp-items="Html.GetEnumSelectList<ClientSex>()"></select>
                    <br />
                    <span asp-validation-for="ClientSex" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="ClientBirthday" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="ClientBirthday" class="formsInput" />
                    <br />
                    <span asp-validation-for="ClientBirthday" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="Weight" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="Weight" class="formsInput" type="number" step="0.1"/>
                    <br />
                    <span asp-validation-for="Weight" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="Height" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="Height" class="formsInput" />
                    <br />
                    <span asp-validation-for="Height" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="LeanMass" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="LeanMass" class="formsInput" type="number" step="0.1"/>
                    <br />
                    <span asp-validation-for="LeanMass" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="FatMass" class="control-label listsItemTitle"></label></th>
                <td>
                    <input asp-for="FatMass" class="formsInput" type="number" step="0.1"/>
                    <br />
                    <span asp-validation-for="FatMass" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th class="alignTableTitles"><label asp-for="OtherClientData" class="control-label listsItemTitle"></label></th>
                <td>
                    <textarea asp-for="OtherClientData" class="descriptionBox"></textarea>
                    <br />
                    <span asp-validation-for="OtherClientData" class="text-danger"></span>
                </td>
            </tr>
        </table>

        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </form>
</div>

@if (User.IsInRole("administrator"))
{
    <div class="backBtnDiv">

        <a asp-controller="Admins" asp-action="ShowAllUsers" class="backToListBtn">Voltar</a>
    </div>
}


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Clients/ShowClients.cshtml
@using NutriFitWeb.Services
@using NutriFitWeb.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UserAccountModel> SignInManager
@inject UserManager<UserAccountModel> UserManager
@model PaginatedList<NutriFitWeb.Models.Client>

<h1>Clientes <img class="iconMargin" src="~/icons/clientIcon.svg" alt="clientsIcon" /></h1>

<input type="submit" value="Ajuda" class="helpBtn" onclick="helpButton()" />

<div class="col-md-4 helpDivs" style="display:none;" id="helpText">
    <p>Aqui pode <b>adicionar</b>, <b>remover</b> e <b>ver os detalhes</b> de <b>Clientes</b>.</p>
</div>

<form asp-action="ShowClients" method="get">
    <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" placeholder="Insira o email do utilizador" class="searchBar" />
    <button type="submit" class="searchBtn"><img class="searchIcon" src="~/icons/searchIcon.svg" alt="searchIcon" /></button>
</form>

@foreach (var item in Model)
{
    <div class="listsDiv">
        <p class="listsItem"><b class="listsItem listsItemTitle showListsBorder">UserName</b> @Html.DisplayFor(modelItem => item.UserAccountModel.UserName)</p>
        <p class="listsItem"><img src="~/icons/emailIcon.svg" /> @Html.DisplayFor(modelItem => item.UserAccountModel.Email)</p>
        <div class="listsItem">
            @if (User.IsInRole("gym"))
            {
                <a asp-action="ChangeClientGymStatus" asp-route-id="@item.ClientId"
           asp-route-pageNumber="@(Model.PageIndex)" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    @if (item.Gym is null)
                    {
                        <img class="addIcon icons" src="~/icons/addIcon.svg" alt="addIcon" />
                    }
                    else if (UserManager.GetUserId(User) == item.Gym.UserAccountModel.Id)
                    {
                        <img class="removeIcon icons" src="~/icons/removeIcon.svg" alt="removeIcon" />
                    }
                </a>
            }
            else if (User.IsInRole("trainer"))
            {
                <a asp-action="ChangeClientTrainerStatus" asp-route-id="@item.ClientId"
           asp-route-pageNumber="@(Model.PageIndex)" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    @if (item.Trainer is null)
                    {
                        <img class="addIcon icons" src="~/icons/addIcon.svg" alt="addIcon" />
                    }
                    else if (UserManager.GetUserId(User) == item.Trainer.UserAccountModel.Id)
                    {
                        <img class="removeIcon icons" src="~/icons/removeIcon.svg" alt="removeIcon" />
                        <a asp-controller="Clients" asp-action="EditClientForTrainerAndNutritionist" asp-route-id="@item.ClientId">
                            <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                        </a>
                    }
                </a>
            }
            else if (User.IsInRole("nutritionist"))
            {
                <a asp-action="ChangeClientNutritionistStatus" asp-route-id="@item.ClientId"
           asp-route-pageNumber="@(Model.PageIndex)" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    @if (item.Nutritionist is null)
                    {
                        <img class="addIcon icons" src="~/icons/addIcon.svg" alt="addIcon" />
                    }
                    else if (UserManager.GetUserId(User) == item.Nutritionist.UserAccountModel.Id)
                    {
                        <img class="removeIcon icons" src="~/icons/removeIcon.svg" alt="removeIcon" />
                        <a asp-controller="Clients" asp-action="EditClientForTrainerAndNutritionist" asp-route-id="@item.ClientId">
                            <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                        </a>
                    }
                </a>
            }
            <a asp-action="ClientDetails" asp-route-id="@item.ClientId"><img class="detailsIcon icons" src="~/icons/detailsIcon.svg" alt="detailsIcon" /></a>
        </div>
    </div>
}

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="pagesDiv">
    @if (prevDisabled != "disabled")
    {
        <a asp-action="ShowClients"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
            <b>Anterior</b>
        </a>
    }

    @if (nextDisabled != "disabled")
    {
        <a asp-action="ShowClients"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
            <b>Próximo</b>
        </a>
    }

    @if (prevDisabled == "disabled" && nextDisabled == "disabled")
    {
        <p class="noMoreResults">Não existem mais resultados</p>
    }
</div>

@if (!string.IsNullOrEmpty(ViewData["CurrentFilter"] as string))
{
    <div class="backBtnDiv">
        <a asp-action="ShowClients" class="backToListBtn">Voltar</a>
    </div>
}