Controllers/ClientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriFitWeb.Data;
using NutriFitWeb.Models;
using NutriFitWeb.Services;

namespace NutriFitWeb.Controllers
{
    /// <summary>
    /// ClientsController Class derives from Controller
    /// </summary>
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserAccountModel> _userManager;
        private readonly IIsUserInRoleByUserId _isUserInRoleByUserId;
        private readonly IPhotoManagement _photoManagement;
        private readonly IInteractNotification _interactNotification;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context">Application DB context</param>
        /// <param name="userManager">User Manager API</param>
        /// <param name="isUserInRoleByUserId">Interface to determine if the user is of a given role</param>
        /// <param name="photoManagement">Photo management Interface</param>
        public ClientsController(ApplicationDbContext context,
            UserManager<UserAccountModel> userManager,
            IIsUserInRoleByUserId isUserInRoleByUserId,
            IPhotoManagement photoManagement,
            IInteractNotification interactNotification)
        {
            _context = context;
            _userManager = userManager;
            _isUserInRoleByUserId = isUserInRoleByUserId;
            _photoManagement = photoManagement;
            _interactNotification = interactNotification;
        }

        /// <summary>
        /// Shows a paginated View of all the clients.
        /// </summary>
        /// <param name="searchString"></param>
        /// <param name="currentFilter"></param>
        /// <param name="pageNumber"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym, nutritionist, trainer")]
        public async Task<IActionResult> ShowClients(string? searchString, string? currentFilter, int? pageNumber)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            if (searchString is not null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            IOrderedQueryable<Client>? clients = null;

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (User.IsInRole("gym"))
            {
                clients = GetClientsForGym(searchString, user.Id);
            }
            else if (User.IsInRole("trainer"))
            {
                clients = await GetClientsForTrainer(searchString, user.Id);
            }
            else if (User.IsInRole("nutritionist"))
            {
                clients = await GetClientsForNutritionist(searchString, user.Id);
            }

            if (clients is not null)
            {
                int pageSize = 3;
                return View(await PaginatedList<Client>.CreateAsync(clients.AsNoTracking(), pageNumber ?? 1, pageSize));
            }
            return NotFound();
        }

        /// <summary>
        /// Shows a specific client details page, based on client id.
        /// </summary>
        /// <param name="id">Client id</param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym, trainer, nutritionist")]
        public async Task<IActionResult> ClientDetails(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            return View(await _context.Client.
                            Include(a => a.UserAccountModel).
                            Include(a => a.Gym).
                            Include(a => a.Trainer).
                            Include(a => a.Nutritionist).
                            Include(a => a.ClientProfilePhoto).
                            FirstOrDefaultAsync(a => a.ClientId == id));
        }

        /// <summary>
        /// Displays the page to change a client's gym status, based on client id.
        /// Only accessible for the Gym role.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="pageNumber"></param>
        /// <param name="currentFilter"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "gym")]
        public async Task<IActionResult> ChangeClientGymStatus(int? id, int? pageNumber, string? currentFilter)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            Gym? gym = await _context.Gym.FirstOrDefaultAsync(a => a.UserAccountModel.Id == user.Id);
            Client? client = await _context.Client.
            Include(a => a.Gym).
            Include(a => a.Trainer).
            Include(a => a.Trainer!.TrainingPlans).
            Include(a => a.Nutritionist).
            Include(a => a.Nutritionist!.NutritionPlans).
            Include(a => a.TrainingPlanRequests).
            Include(a => a.NutritionPlanRequests).
            Include(a => a.UserAccountModel).
            FirstOrDefaultAsync(a => a.ClientId == id);

            if (client is not null && client.UserAccountModel is not null)
            {
                if (gym is not null && client.Gym is null ||
                                    (client.Gym is not null && client.Gym.UserAccountModel is not null &&
                                    _userManager.GetUserId(User) == client.Gym.UserAccountModel.Id))
                {
                    client.Gym = (client.Gym is null) ? gym : null;
                    if (client.Gym is null)
                    {
                        if (client.Trainer is not null && client.Trainer.TrainingPlans is not null)
                        {
                            client.Trainer.TrainingPlans = client.Trainer.TrainingPlans.Where(a => a.Client != client).ToList();
                        }
                        if (client.Nutritionist is not null && client.Nutritionist.NutritionPlans is not null)
                        {
                            client.Nutritionist.NutritionPlans = client.Nutritionist.NutritionPlans.Where(a => a.Client != client).ToList();
                        }
                        client.Trainer = null;
                        client.WantsTrainer = false;
                        client.Nutritionist = null;
                        client.WantsNutritionist = false;
                        client.TrainingPlanRequests = null;
                        client.NutritionPlanRequests = null;
                        client.DateAddedToGym = null;
                        await _interactNotification.Create("Foi removido do seu ginásio.", client.UserAccountModel);
                    }
                    else
                    {
                        client.DateAddedToGym = DateTime.Now;
                        await _interactNotification.Create($"Foi adicionado ao ginásio {client.Gym.GymName}.", client.UserAccountModel);
                    }
                    _context.Client.Update(client);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("ShowClients", new { pageNumber, currentFilter });
            }
            return NoContent();
        }

        /// <summary>
        /// Displays the page to change a client's trainer status, based on client id.
        /// Only accessible for the Trainer role.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="pageNumber"></param>
        /// <param name="currentFilter"></param>
        /// <returns>An Action result</returns>
        [Authorize(Roles = "trainer")]
        public async Task<IActionResult> ChangeClientTrainerStatus(int? id, int? pageNumber, string? currentFilter)
        {
            if (User.Identity is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            Trainer? trainer = await _context.Trainer.Include(a => a.UserAccountModel).FirstOrDefaultAsync(a => a.UserAccountModel.Id == user.Id);
            Client? client = await _context.Client.
            Include(a => a.Trainer).
            Include(a => a.Trainer!.TrainingPlans).
            Include(a => a.UserAccountModel).
            FirstOrDefaultAsync(a => a.ClientId == id);

            if (client is not null && client.UserAccountModel is not null &&
                trainer is not null && trainer.UserAccountModel is not null)
            {
                if (client.Gym == trainer.Gym && client.Trainer is null ||
                (client.Trainer is not null && client.Trainer.UserAccountModel is not null &&
                _userManager.GetUserId(User) == client.Trainer.UserAccountModel.Id))
                {
                    if (client.Trainer is not null && client.Trainer.TrainingPlans is not null)
                    {
                        client.Trainer.TrainingPlans = client.Trainer.TrainingPlans.Where(a => a.Client != client).ToList();
                    }
                    client.Trainer = (client.Trainer is null) ? trainer : null;
                    if (client.Trainer is null)
                    {
                        client.DateAddedToTrainer = null;
                        await _interactNotification.Create($"O {trainer.UserAccountModel.UserName} já não é seu treinador.", client.UserAccountModel);
                    }
                    else
                    {
                        client.DateAddedToTrainer = DateTime.Now;

Controllers/GymsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NutriFitWeb.Data;
using NutriFitWeb.Models;
using NutriFitWeb.Services;

namespace NutriFitWeb.Controllers
{
    /// <summary>
    /// GymsController class, derives from Controller
    /// </summary>
    public class GymsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserAccountModel> _userManager;
        private readonly IIsUserInRoleByUserId _isUserInRoleByUserId;
        private readonly IPhotoManagement _photoManagement;
        private readonly IInteractNotification _interactNotification;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context">Application DB context API</param>
        /// <param name="userManager">User manager API</param>
        /// <param name="inRoleByUserId">Interface for roles by user id</param>
        /// <param name="photoManagement">Photo management Interface</param>
        public GymsController(ApplicationDbContext context,
            UserManager<UserAccountModel> userManager,
            IIsUserInRoleByUserId inRoleByUserId,
            IPhotoManagement photoManagement,
            IInteractNotification interactNotification)
        {
            _context = context;
            _userManager = userManager;
            _isUserInRoleByUserId = inRoleByUserId;
            _photoManagement = photoManagement;
            _interactNotification = interactNotification;
        }

        /// <summary>
        /// Displays the page to edit the gym settings.
        /// Only accessible to Administrator and Gym roles.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A View result</returns>
        [Authorize(Roles = "administrator, gym")]
        public async Task<IActionResult> EditGymSettings(string? id)
        {
            if (string.IsNullOrEmpty(id) || User.Identity is null)
            {
                return BadRequest();
            }

            Gym? gym = await GetGym(id);
            if (gym is not null && gym.GymProfilePhoto is not null)
            {
                gym.GymProfilePhoto.PhotoUrl = await _photoManagement.LoadProfileImage(gym.UserAccountModel.UserName);
            }

            if (gym is null)
            {
                return NotFound();
            }
            return View(gym);
        }

        /// <summary>
        /// HTTP Post method on the API to edit the gym settings.
        /// Only accessible to Administrator and Gym roles.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="formFile"></param>
        /// <returns>View result</returns>
        [HttpPost, ActionName("EditGymSettings")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator, gym")]
        public async Task<IActionResult> EditGymSettingsPost(string? id, IFormFile? formFile)
        {
            if (string.IsNullOrEmpty(id) || User.Identity is null)
            {
                return BadRequest();
            }

            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity.Name);
            Gym? gymToUpdate = await GetGym(id);

            Photo? oldPhoto = null;

            if (gymToUpdate is null || gymToUpdate.UserAccountModel is null)
            {
                return NotFound();
            }

            if (gymToUpdate.GymProfilePhoto is not null)
            {
                oldPhoto = gymToUpdate.GymProfilePhoto;
            }
            gymToUpdate.GymProfilePhoto = _photoManagement.UploadProfilePhoto(formFile);

            if (await TryUpdateModelAsync<Gym>(gymToUpdate, "",
                g => g.GymName!, g => g.GymProfilePhoto!))
            {
                if (oldPhoto is not null && gymToUpdate.GymProfilePhoto is not null)
                {
                    _context.Photos.Remove(oldPhoto);
                }
                else if (gymToUpdate.GymProfilePhoto is null)
                {
                    gymToUpdate.GymProfilePhoto = oldPhoto;
                }

                if (gymToUpdate.GymProfilePhoto is not null)
                {
                    gymToUpdate.GymProfilePhoto.PhotoUrl = await _photoManagement.LoadProfileImage(User.Identity.Name);
                }
                if (await _isUserInRoleByUserId.IsUserInRoleByUserIdAsync(user.Id, "administrator"))
                {
                    await _interactNotification.Create($"O administrador alterou parte do seu perfil.", gymToUpdate.UserAccountModel);
                    return RedirectToAction("ShowAllUsers", "Admins");
                }
                await _context.SaveChangesAsync();
                return View(gymToUpdate);
            }
            return View(gymToUpdate);
        }

        /// <summary>
        /// Get a gym by id
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A query with the Gym details</returns>
        private async Task<Gym> GetGym(string? id)
        {
            UserAccountModel? user = await _userManager.FindByNameAsync(User.Identity!.Name);
            if (await _isUserInRoleByUserId.IsUserInRoleByUserIdAsync(user.Id, "administrator"))
            {
                return _context.Gym
                    .Include(a => a.UserAccountModel)
                    .Include(a => a.GymProfilePhoto).FirstOrDefault(a => a.UserAccountModel.Id == id);
            }

            UserAccountModel? userAccount = await _userManager.FindByNameAsync(id);
            return await _context.Gym
                .Include(a => a.UserAccountModel)
                .Include(a => a.GymProfilePhoto).FirstOrDefaultAsync(a => a.UserAccountModel == userAccount);
        }
    }
}

Views/Admins/DeleteUserAccount.cshtml
@model NutriFitWeb.Models.UserAccountModel


<h2>Tem a certeza que pretende desativar esta conta?</h2>
<div class="col-md-6 profileDivs">
<table class="formTables">
    <tr>
        <th><p class="control-label listsItemTitle">Username</p></th>
        <td><p class="itemsLeftMargin"><b>@Html.DisplayFor(model => model.UserName)</b></p></td>
    </tr>
    <tr>
        <th><p class="control-label listsItemTitle">Email</p></th>
        <td><p><b>@Html.DisplayFor(model => model.Email)</b></p></td>
    </tr>
</table>

<form asp-action="DeleteUserAccount">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Desativar Conta" class="btn btn-danger" />
</form>
</div>

<div class="backBtnDiv">
    <a asp-action="ShowAllUsers" class="backToListBtn">Voltar</a>
</div>

Views/Admins/EditUserSettings.cshtml
@model NutriFitWeb.Models.UserAccountModel

@{
    ViewData["Title"] = "Editar Definições de Conta";
}

<h1>@ViewData["Title"]</h1>

<div class="col-md-6 profileDivs exercisesDiv">
    <form asp-action="EditUserSettings">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <table class="formTables">
                <tr>
                    <th class="alignTableTitles"><label asp-for="UserName" class="control-label listsItemTitle" ></label></th>
                    <td>
                        <input asp-for="UserName" class="formsInput" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <th class="alignTableTitles"><label asp-for="PhoneNumber" class="control-label listsItemTitle">Telemóvel</label></th>
                    <td>
                        <input type="number" asp-for="PhoneNumber" class="formsInput" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </td>
                </tr>
        </table>
        <div class="form-group">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </form>
</div>

<div class="backBtnDiv">
    <a asp-action="ShowAllUsers" class="backToListBtn">Voltar</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Admins/ShowAllUsers.cshtml
@model PaginatedList<NutriFitWeb.Models.UserAccountModel>
@using NutriFitWeb.Services

@inject IIsUserInRoleByUserId IsUserInRoleByUserId

@{
    ViewData["Title"] = "ShowAllUsers";
}

<h1>Lista de Utilizadores <img class="iconMargin" src="~/icons/clientIcon.svg" alt="clientsIcon" /></h1>

<input type="submit" value="Ajuda" class="helpBtn" onclick="helpButton()" />

<div class="col-md-4 helpDivs" style="display:none;" id="helpText">
    <p>Aqui pode ver todos os utilizadores da aplicação. Pode <b>desativar contas</b>, <b>editar</b> dados de <b>perfil</b> e dados de <b>conta</b>.</p>
</div>

<form asp-action="ShowAllUsers" method="get">
    <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" placeholder="Insira o email do utilizador" class="searchBar" />
    <button type="submit" class="searchBtn"><img class="searchIcon" src="~/icons/searchIcon.svg" alt="searchIcon" /></button>
</form>
@foreach (var item in Model)
{

    <div class="listsDiv">
        <p class="listsItem"><b class="listsItem listsItemTitle showListsBorder allUsersTitleFix">UserName </b> &nbsp; @Html.DisplayFor(modelItem => item.UserName)</p>
        <p class="listsItem"><img src="~/icons/emailIcon.svg"/> @Html.DisplayFor(modelItem => item.Email)</p>
        <div class="listsItem">
            <a asp-action="DeleteUserAccount" asp-route-id="@item.Id"><img class="removeIcon icons" src="~/icons/removeIcon.svg" alt="removeIcon" /></a>

            <a asp-action="EditUserSettings" asp-route-id="@item.Id"><img class="editProfileIcon icons" src="~/icons/editIcon.svg" alt="editIcon" /></a>

            @if (await IsUserInRoleByUserId.IsUserInRoleByUserIdAsync(item.Id, "client"))
            {
                <a asp-controller="Clients" asp-action="EditClientSettings" asp-route-id="@item.Id">
                    <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                </a>
            }
            @if (await IsUserInRoleByUserId.IsUserInRoleByUserIdAsync(item.Id, "nutritionist"))
            {
                <a asp-controller="Nutritionists" asp-action="EditNutritionistSettings" asp-route-id="@item.Id">
                    <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                </a>
            }
            @if (await IsUserInRoleByUserId.IsUserInRoleByUserIdAsync(item.Id, "trainer"))
            {
                <a asp-controller="Trainers" asp-action="EditTrainerSettings" asp-route-id="@item.Id">
                    <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                </a>
            }
            @if (await IsUserInRoleByUserId.IsUserInRoleByUserIdAsync(item.Id, "gym"))
            {
                <a asp-controller="Gyms" asp-action="EditGymSettings" asp-route-id="@item.Id">
                    <img class="editIcon" src="~/icons/editProfileIcon.svg" alt="editProfileIcon" />
                </a>
            }
        </div>
    </div>
}

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="pagesDiv">
    @if (prevDisabled != "disabled")
    {
        <a asp-action="ShowAllUsers"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
            <b>Anterior</b>
        </a>
    }

    @if (nextDisabled != "disabled")
    {
        <a asp-action="ShowAllUsers"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
            <b>Próximo</b>
        </a>
    }

    @if (prevDisabled == "disabled" && nextDisabled == "disabled")
    {
        <p class="noMoreResults">Não existem mais resultados</p>
    }
</div>

@if (!string.IsNullOrEmpty(ViewData["CurrentFilter"] as string))
{
    <div class="backBtnDiv">
        <a asp-action="ShowAllUsers" class="backToListBtn">Voltar</a>
    </div>
}

Views/Admins/_AdminHome.cshtml
@using NutriFitWeb.Services
@using Microsoft.AspNetCore.Identity

@{
    ViewData["Title"] = "Admin Home Page";
}

<h1>Bem Vindo Administrador!</h1>
<p>Clique na opção <b><i>Utilizadores</i></b> para editar perfis ou eliminar utilizadores.</p>
<img src="~/images/admin.png" alt="MainPageAdminImage" class="notLoggedInHome imageHome" />