Models/Meal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace NutriFitWeb.Models
{
    /// <summary>
    /// Meal class, implements IValidatableObject
    /// </summary>
    public class Meal : IValidatableObject
    {
        /// <summary>
        /// Gets and Sets the Meal id.
        /// </summary>
        public int MealId { get; set; }
        /// <summary>
        /// Gets and Sets the Meal name.
        /// </summary>
        [Required(ErrorMessage = "Este campo é obrigatório.")]
        [StringLength(20, ErrorMessage = "O nome não pode exceder 20 caracteres.")]
        public string? MealName { get; set; }
        /// <summary>
        /// Gets and Sets the Meal description.
        /// </summary>
        [StringLength(1000, ErrorMessage = "A descrição não pode exceder 1000 caracteres.")]
        public string? MealDescription { get; set; }
        /// <summary>
        /// Gets and Sets the Meal calories.
        /// </summary>
        [Range(1, 99999, ErrorMessage = "Uma refeição deve conter entre {1} e {2} calorias.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Deve inserir um valor inteiro.")]
        public int? MealCalorie { get; set; }
        /// <summary>
        /// Gets and Sets the Meal protein value.
        /// </summary>
        [Range(1, 99999, ErrorMessage = "Uma refeição deve conter entre {1} e {2} gramas de proteína.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Deve inserir um valor inteiro.")]
        public int? MealProtein { get; set; }
        /// <summary>
        /// Gets and Sets the Meal fat value.
        /// </summary>
        [Range(1, 99999, ErrorMessage = "Uma refeição deve conter entre {1} e {2} gramas de gordura.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Deve inserir um valor inteiro.")]
        public int? MealFat { get; set; }
        /// <summary>
        /// Gets and Sets the Meal carbohydrate value.
        /// </summary>
        [Range(1, 99999, ErrorMessage = "Uma refeição deve conter entre {1} e {2} gramas de hidratos de carbono.")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Deve inserir um valor inteiro.")]
        public int? MealCarbohydrate { get; set; }
        /// <summary>
        /// Gets and Sets the Meal target date.
        /// </summary>

        [DataType(DataType.Date)]
        public DateTime? MealDate { get; set; }
        /// <summary>
        /// Gets the Sets the Meal target week day.
        /// </summary>

        [Column(TypeName = "nvarchar(24)")]
        public MealWeekDay? MealWeekDay { get; set; }
        /// <summary>
        /// Gets and Sets the Meal type.
        /// </summary>

        [Column(TypeName = "nvarchar(24)")]
        public MealType? MealType { get; set; }
        /// <summary>
        /// Gets and Sets the Meal url.
        /// </summary>

        [Url(ErrorMessage = "Este URL tem de estar no formato http, https, or ftp.")]
        public string? MealURL { get; set; }
        /// <summary>
        /// Gets and Sets the Meal associated nutrition plan.
        /// </summary>

        [JsonIgnore]
        public NutritionPlan? NutritionPlan { get; set; }
        /// <summary>
        /// Gets and Sets the Meal photo.
        /// </summary>
        public Photo? MealPhoto { get; set; }

        /// <summary>
        /// Validation function to validate the MealDate and MealWeekDay
        /// </summary>
        /// <param name="validationContext"></param>
        /// <returns></returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (MealDate is null && MealWeekDay is null)
            {
                yield return new ValidationResult(
                    "Pelo menos uma data ou um dia de semana têm de ser fornecidos.",
                    new[] { nameof(MealDate), nameof(MealWeekDay) });
            }
            if (MealDate is not null && MealWeekDay is not null)
            {
                yield return new ValidationResult(
                    "Apenas pode fornecer uma data ou um dia de semana.",
                    new[] { nameof(MealDate), nameof(MealWeekDay) });
            }
            yield return ValidationResult.Success;
        }
    }

    public enum MealType
    {
        [Display(Name = "Pequeno Almoço")]
        BREAKFAST,
        [Display(Name = "Almoço")]
        LUNCH,
        [Display(Name = "Jantar")]
        DINER
    }

    public enum MealWeekDay
    {
        [Display(Name = "Domingo")]
        SUNDAY,
        [Display(Name = "Segunda-Feira")]
        MONDAY,
        [Display(Name = "Terça-Feira")]
        TUESDAY,
        [Display(Name = "Quarta-Feira")]
        WEDNESDAY,
        [Display(Name = "Quinta-Feira")]
        THURSDAY,
        [Display(Name = "Sexta-Feira")]
        FRIDAY,
        [Display(Name = "Sábado")]
        SATURDAY
    }
}

Controllers/MealsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NutriFitWeb.Models;
using NutriFitWeb.Services;

namespace NutriFitWeb.Controllers
{
    [Authorize(Roles = "client, nutritionist")]
    /// <summary>
    /// MealsController, derives from Controller
    /// </summary>
    public class MealsController : Controller
    {
        private readonly string SessionKeyMeals;
        private readonly string SessionKeyPhoto;
        private readonly IPhotoManagement _photoManagement;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="photoManagement">Photo management interface</param>
        public MealsController(IPhotoManagement photoManagement)
        {
            SessionKeyMeals = "_Meals";
            SessionKeyPhoto = "_Photo";
            _photoManagement = photoManagement;
        }

        /// <summary>
        /// Renders a partial view for a list of meals.
        /// </summary>
        /// <returns>A PartialView result</returns>
        public IActionResult ShowMealsList()
        {
            List<Meal>? meals = HttpContext.Session.Get<List<Meal>>(SessionKeyMeals);
            if (meals is not null)
            {
                meals = HttpContext.Session.Get<List<Meal>>(SessionKeyMeals);
                return PartialView("_ShowMealsPartial", meals);
            }

            return PartialView("_ShowMealsPartial", new List<Meal>());
        }

        /// <summary>
        /// HTTP POST action on the API to Create a meal.
        /// </summary>
        /// <param name="meal"></param>
        /// <param name="formFile"></param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void CreateMeal([Bind("MealId,MealName,MealDescription,MealCalorie,MealProtein,MealFat,MealCarbohydrate,MealDate,MealWeekDay,MealType,MealURL")] Meal meal,
            IFormFile? formFile)
        {
            if (ModelState.IsValid)
            {
                List<Meal>? meals;
                Photo? oldPhoto = HttpContext.Session.Get<Photo>(SessionKeyPhoto);
                Photo? newPhoto = _photoManagement.UploadProfilePhoto(formFile);
                if ((oldPhoto is not null && newPhoto is not null) || (newPhoto is not null && oldPhoto is null))
                {
                    meal.MealPhoto = newPhoto;
                }
                else
                {
                    meal.MealPhoto = oldPhoto;
                }
                if (HttpContext.Session.Get<List<Meal>>(SessionKeyMeals) is null)
                {
                    HttpContext.Session.Set<List<Meal>>(SessionKeyMeals, new List<Meal>() { meal });
                }
                else
                {
                    meals = HttpContext.Session.Get<List<Meal>>(SessionKeyMeals);
                    if (meals is not null)
                    {
                        meals.Add(meal);
                        HttpContext.Session.Set<List<Meal>>(SessionKeyMeals, meals);
                    }
                }
            }
        }

        /// <summary>
        /// Renders a partial view to edit a meal, given the meal's id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A PartialView result</returns>
        public IActionResult EditMeal(int id)
        {
            List<Meal>? meals = HttpContext.Session.Get<List<Meal>>(SessionKeyMeals);

            if (meals is null)
            {
                return NotFound();
            }

            Meal meal = meals[id];
            meals.RemoveAt(id);
            HttpContext.Session.Set<List<Meal>>(SessionKeyMeals, meals);
            if (meal.MealPhoto is not null)
            {
                HttpContext.Session.Set<Photo>(SessionKeyPhoto, meal.MealPhoto);
            }
            return PartialView("_CreateMealPartial", meal);
        }

        /// <summary>
        /// Renders a partial view to delete a meal, given the meal id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A PartialView result</returns>
        public IActionResult DeleteMeal(int id)
        {
            List<Meal>? meals = HttpContext.Session.Get<List<Meal>>(SessionKeyMeals);
            if (meals is not null)
            {
                meals.RemoveAt(id);
                HttpContext.Session.Set<List<Meal>>(SessionKeyMeals, meals);

                return PartialView("_ShowMealsPartial", meals);
            }

            return PartialView("_ShowMealsPartial", new List<Exercise>());
        }

        /// <summary>
        /// Renders a partial view to create a a Meal.
        /// </summary>
        /// <returns>A PartialView result</returns>
        public IActionResult GetCleanCreateMealPartial()
        {
            return PartialView("_CreateMealPartial");
        }
    }
}

Views/Meals/_CreateMealPartial.cshtml
@using NutriFitWeb.Services
@model NutriFitWeb.Models.Meal
@inject IPhotoManagement PhotoManagement

<div class="col-md-12 profileDivs exercisesDiv tableWrapper">
    <h2>Adicionar refeição</h2>
    <form method="post" id="_CreateMealPartialForm" data-ajax-begin="UpdateCreateMeal" data-ajax-success="UpdateMealsList" data-ajax="true"
          asp-action="CreateMeal" asp-controller="Meals" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="MealPhoto" class="control-label listsItemTitle">Foto da Refeição</label>
            @if (Model is not null && Model.MealPhoto is not null)
            {
                string? mealPhoto = PhotoManagement.GetPhotoPath(Model.MealPhoto);
                <div><img class="profilePhoto" src="@mealPhoto" /></div>
            }
            <input type="file" asp-for="MealPhoto" class="form-control marginFixChooseFile" name="formFile" />
            <span asp-validation-for="MealPhoto" class="text-danger"></span>
        </div>

        <table class="formTables">
            <tr>
                <th class="alignTableTitles"><label asp-for="MealName" class="control-label">Nome</label></th>
                <td>
                    <input asp-for="MealName" class="formsInput" />
                    <br />
                    <span asp-validation-for="MealName" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <th><label asp-for="MealDescription" class="control-label">Descrição</label></th>
                <td>
                    <textarea asp-for="MealDescription" class="descriptionBox"></textarea>
                    <span asp-validation-for="MealDescription" class="text-danger"></span>
                </td>
            </tr>
        </table>

        <table class="formTables">
            <tr>
                <th><label asp-for="MealCalorie" class="control-label">Calorias</label></th>
                <th><label asp-for="MealProtein" class="control-label">Proteína</label></th>
            </tr>
            <tr>
                <td>
                    <input asp-for="MealCalorie" class="formsInput" />
                    <span asp-validation-for="MealCalorie" class="text-danger"></span>
                </td>
                <td>
                    <input asp-for="MealProtein" class="formsInput" />
                    <span asp-validation-for="MealProtein" class="text-danger"></span>
                </td>
            </tr>
        </table>

        <table class="formTables">
            <tr>
                <th><label asp-for="MealFat" class="control-label">Gordura</label></th>
                <th><label asp-for="MealCarbohydrate" class="control-label">Carboidratos</label></th>
            </tr>
            <tr>
                <td>
                    <input asp-for="MealFat" class="formsInput" />
                    <span asp-validation-for="MealFat" class="text-danger"></span>
                </td>
                <td>
                    <input asp-for="MealCarbohydrate" class="formsInput" />
                    <span asp-validation-for="MealCarbohydrate" class="text-danger"></span>
                </td>
            </tr>
        </table>

        <table class="formTables">
            <label for="dateOrWeekDaySelect" class="control-label">Data/Dia da Semana</label>
            <select class="formsInput selectDropDwn" name="dateOrWeekDaySelect" onchange="showDateOrWeekDayDiv(this)" id="dateOrWeekDaySelect">
                <option value="1">Data</option>
                <option value="2">Dia de Semana</option>
            </select>
            <div style="display:block;" id="MealDateID">
                <input required="true" id="MealDateInputID" asp-for="MealDate" class="formsInput" />
                <br />
                <span asp-validation-for="MealDate" class="text-danger"></span>
            </div>
            <div style="display:none;" id="MealWeekDayID">
                <select required="true" id="MealWeekDaySelectID" asp-for="MealWeekDay" class="formsInput" asp-items="Html.GetEnumSelectList<MealWeekDay>()">
                    <option value="">Selecione um dia da semana</option>
                </select>
                <br />
                <span asp-validation-for="MealWeekDay" class="text-danger"></span>
            </div>
        </table>

        <table class="formTables">
            <tr>
                <th><label asp-for="MealType" class="control-label">Tipo</label></th>
                <th><label asp-for="MealURL" class="control-label">Link da refeição</label></th>
            </tr>
            <tr>
                <td>
                    <select asp-for="MealType" class="formsInput" asp-items="Html.GetEnumSelectList<MealType>()"></select>
                    <span asp-validation-for="MealType" class="text-danger"></span>
                </td>
                <td>
                    <input asp-for="MealURL" class="formsInput" />
                    <span asp-validation-for="MealURL" class="text-danger"></span>
                </td>
            </tr>
        </table>

        <div><input type="submit" value="Adicionar" class="btn btn-primary" /></div>
    </form>
</div>

@section Scripts {

    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Views/Meals/_ShowMealsDetailsPartial.cshtml
@using NutriFitWeb.Services
@model IEnumerable<NutriFitWeb.Models.Meal>
@inject IPhotoManagement PhotoManagement

<br />
<p class="listsItemTitle">Refeições</p>

<table class="table exercisesMealsTable">
    <thead class="tableHeader">
        <tr>
            <th class="roundedCornerTableLeft thStyle">
                Nome/Descrição
            </th>
            <th class="thStyle">
                Foto
            </th>
            <th class="roundedCornerTableRight thStyle">
                Outros Dados
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td class="exercisesData breakText breakTextOtherData">
                        <p>@Html.DisplayFor(modelItem => item.MealName)</p>
                        <br />
                        <p>@Html.DisplayFor(modelItem => item.MealDescription)</p>
                    </td>
                    <td>
                        @if (item.MealPhoto is not null)
                        {
                            string? mealPhoto = PhotoManagement.GetPhotoPath(item.MealPhoto);
                            <img class="profilePhoto" src="@mealPhoto" />
                        }else{
                            <p class="exercisesData">N/A</p>
                        }
                    </td>
                    <td class="exercisesData">
                        @if (item.MealDate is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealDate)
                                @if (item.MealCalorie is not null
                               || item.MealProtein is not null
                               || item.MealFat is not null
                               || item.MealCarbohydrate is not null
                               || item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealWeekDay is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealWeekDay)
                                @if (item.MealCalorie is not null
                               || item.MealProtein is not null
                               || item.MealFat is not null
                               || item.MealCarbohydrate is not null
                               || item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealCalorie is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealCalorie) calorias
                                @if (item.MealProtein is not null
                               || item.MealFat is not null
                               || item.MealCarbohydrate is not null
                               || item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealProtein is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealProtein)g de proteína
                                @if (item.MealFat is not null
                               || item.MealCarbohydrate is not null
                               || item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealFat is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealFat)g de gordura
                                @if (item.MealCarbohydrate is not null
                               || item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealCarbohydrate is not null)
                        {
                            <p>
                                @Html.DisplayFor(modelItem => item.MealCarbohydrate)g de carboidratos
                                @if (item.MealURL is not null)
                                {
                                    <b>,</b>
                                }
                            </p>
                        }
                        @if (item.MealURL is not null && item.MealURL != "")
                        {
                            <a class="videosUrl" href="@item.MealURL" target="_blank">Link da refeição</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Views/Meals/_ShowMealsPartial.cshtml
@model IEnumerable<NutriFitWeb.Models.Meal>


<h2 class="h2Fix">Refeições</h2>

<table class="table">
    <thead class="tableHeader">
        <tr>
            <th class="roundedCornerTableLeft thStyle">
                Nome da Refeição
            </th>
            <th class="thStyle">
                Descrição
            </th>
            <th class="roundedCornerTableRight thStyle">Ações</th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
        {
            @foreach (var item in Model.Select((value, i) => new { i, value }))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.value.MealName)
                    </td>
                    <td>
                        @if (String.IsNullOrEmpty(item.value.MealDescription))
                        {
                            <p>N/A</p>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.value.MealDescription)
                        }
                    </td>
                    <td>
                        <a asp-action="DeleteMeal" asp-controller="Meals" data-ajax="true" data-ajax-update="#_ShowMealsPartialList"
                   asp-route-id="@item.i"><img class="removeIcon icons" src="~/icons/removeIcon.svg" /></a>
                        <a asp-action="EditMeal" asp-controller="Meals" data-ajax="true" data-ajax-success="UpdateMealsList"
                   data-ajax-update="#_CreateMealPartialItem" asp-route-id="@item.i"><img class="editIcon" src="~/icons/editProfileIcon.svg" /></a>
                    </td>
                </tr>
            }

        }
    </tbody>
</table>
<br />